name: Environments Demo

on:
  workflow_dispatch:
  
env:
  USERNAME: rajbos
  
jobs:
  deploy-to-devtest:
    runs-on: ubuntu-latest
    environment: DevTest
    
    steps: 
      - run: echo "Hello world from DevTest"
      - run: echo "My secret value = [${{ secrets.DEMO_SECRET }}] for user [$USERNAME]"

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: deploy-to-devtest
    environment: Production
    
    steps: 
      - run: echo "Hello world from Production"
      - run: echo "My secret value = [${{ secrets.DEMO_SECRET }}] for user [$USERNAME]"
