on:
  push:
    paths:
    - .github/workflows/job-summary.yml
    
  workflow_dispatch:
  
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - name: Write to job summary
      run: |
         echo "GITHUB_STEP_SUMMARY = [$GITHUB_STEP_SUMMARY]"
         echo "" >> $GITHUB_STEP_SUMMARY
         echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
    
    - name: Write to job summary again
      run: |
         echo "GITHUB_STEP_SUMMARY2 = [$GITHUB_STEP_SUMMARY]"
         echo "" >> $GITHUB_STEP_SUMMARY
         echo '### Hello world! :smile:' >> $GITHUB_STEP_SUMMARY

  demo-two:
    runs-on: ubuntu-latest
    steps:
    - name: Write to job summary
      run: |
         echo "GITHUB_STEP_SUMMARY = [$GITHUB_STEP_SUMMARY]"
         echo "" >> $GITHUB_STEP_SUMMARY
         echo '![#power](https://giphy.com/embed/26uf3G9yrXSn4ChLG)' >> $GITHUB_STEP_SUMMARY
